//#include "sdk/monoString.h"
#include <vector>
#include <string>
#include <fstream>
#include <dirent.h>
#include <thread>
#include <atomic>
#include <cstdint>
#include <cmath>
#include <cctype>
#include <string>
#include <deque>
#include <map>
#include <type_traits>
#include <initializer_list>
#include <ostream>
#include <iostream>
#include <map>
#include "imgui.h"
#include <vector>
#include <array>

#include "sdk/encryption/hiden_imports.h"
#include "sdk/encryption/oxorany.cpp"
#include "sdk/encryption/oxorany.h"
#include "sdk/encryption/oxorany_include.h"

#include "sdk/process.h"
#include "sdk/bools.h"
#include "sdk/widgets/widgets.h"
#include "sdk/skinchanger.h"
#include "sdk/json/json.h"
#include "sdk/configuration/configs.h"
#include "sdk/texture_helper.h"
#include "sdk/game.h"
#include "sdk/player.h"
#include "sdk/recorder/recorder.h"
#include "sdk/interface/menu.h"
#include "sdk/functions.h"
#include "sdk/granades.h"
#include "sdk/weapons.h"